title: SKY Network Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://status.skyfs.net'
params:
  disableDarkMode: false
  shortDateFormat: '15:04 — Jan 2'
  down: '#e60000'
  systems:
    - name: Website
      description: The main website
      category: Sky Network
    - name: Discord Bot
      category: Discord Bots
      description: The main discord bot for Sky Network
    - name: Role Discord Bot
      category: Discord Bots
      description: The Authentication and Role bot for discord
    - name: Status Discord Bot
      category: Discord Bots
      description: The FiveM Status Bot for Discord
    - name: Status Page
      description: Status Page
      category: Sky Network
    - name: DNS Server 1
      description: >-
        Allows you to use play.skyfs.net because we know you cant be bothered to
        copy and paste some numbers.
      category: Sky Network
    - name: DNS Server 2
      description: Backup DNS Servers
      category: Sky Network
    - name: FM Server 1
      description: This is the main FS Server
      category: Sky Network Flight Simulator
    - name: FM Server 2
      description: This is the secondary FS Server
      category: Sky Network Flight Simulator
    - name: FM Dev Server
      description: This is the development FS Server
      category: Sky Network Flight Simulator
    - name: RP Server 1
      description: This is the main County RP Server
      category: Sky Network County RP
    - name: RP Server 2
      description: This is the secondary County RP Server
      category: Sky Network County RP
    - name: RP Dev Server
      description: This is the development County RP Server
      category: Sky Network County RP
    - name: MC Server 1
      description: This is the Main MC Server
      category: Sky Network MC
    - name: MC Dev Server
      description: This is the Development MC Server
      category: Sky Network MC
  dateFormat: 'January 2, 2006 at 3:04 PM'
  brand: '#0a0c0f'
  headerTextColor: white
  logo: /logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: '#cc4400'
  notice: '#24478f'
  incidentHistoryFormat: monthly
  ok: '#008000'
  categories:
    - name: Sky Network
      description: All global services for the Sky Network.
    - name: Discord Bots
      closed: false
      untited: false
      description: The Sky Network Discord Bots
    - name: Sky Network Flight Simulator
      description: All related services for Sky Network Flight Simulator are located here.
    - name: Sky Network County RP
      description: All related services for Sky Network County RP are located here.
    - name: Sky Network MC
      description: All related services for Sky Network Minecraft Server are located here.
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  useLargeHeaderDesign: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
